### ISSUE TITLE
Fix these issues

### ISSUE THREAD

**Issue by varunon9** [gawdsnitkkr/Techspardha-2017-Admin-Apnel#12]
1. Replace the 'Event' (in tab) with actual event name 
2. message.svg and lock.svg (login screen icon) - 404 error
3. while updating event, error message is please correct the red boxes. However there are no such red boxes. I tried updating event description, rules and maximum contestant
4. has notify been implemented?

**Comment by AnshulMalik** [comment]
Notifications are not yet incorporated. will soon be added.
